QnA/urls.py
from django.urls import path
from . import views


app_name = 'QnA'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:q_id>/', views.question, name='question'),
    path('<int:q_id>/next_question/', views.next_question, name='next_question'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    # path('<str:username>/', views.profile, name='profile'),
    # path('<str:username>/follow', views.follow, name='follow')
]

ballance/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('QnA/', include('QnA.urls')),
    path('accounts/', include('accounts.urls')),
]

QnA/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Question(models.Model):
    content = models.CharField(max_length=200)
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # answer_set

class Answer(models.Model):
    option = models.BooleanField()
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# from django_resized import ResizedImageField
# Create your models here.

class User(AbstractUser):
    pass
    # profile_image = ResizedImageField(
    #     size = [500, 500],
    #     crop = ['middle', 'center'],
    #     upload_to='profile',
    # )

    # followings = models.ManyToManyField('self', related_name='followers', symmetrical=False)

QnA/forms.py
from django.forms import ModelForm
from .models import Question

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = '__all__'
        

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = get_user_model()
        fields = ('username', )


class CustomAuthenticationForm(AuthenticationForm):
    pass
    # class Meta:
    #     model = User
    #     fields = ('username', )

QnA/views.py
from django.shortcuts import render, redirect
from .models import Question
from .forms import QuestionForm
# Create your views here.

def index(request):
    questions = Question.objects.all()
    first_question = Question.objects.get(id=1)

    context = {
        'questions': questions,
        'q_id': first_question.id,
    }

    return render(request, 'index.html', context)



def question(request, q_id):
    question = Question.objects.get(id=q_id)
    
    context = {
        'question': question,
        'q_id' : question.id,
        
    }

    return render(request, 'question.html', context)




def next_question(request, q_id):
    next_question = Question.objects.get(id=2)



    return redirect(f'/QnA/{next_question.id}/')

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
# Create your views here.

def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('posts:index')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/form.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('posts:index')
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_url = request.GET.get('next')
            return redirect(next_url or 'posts:index')
    else:
        form = CustomAuthenticationForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/form.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

def profile(request, username):
    User = get_user_model()
    user_info = User.objects.get(username=username)

    context = {
        'user_info': user_info,
    }

    return render(request, 'accounts/profile.html', context)

# @login_required
# def follow(request, username):
#     me = request.user
#     you = get_user_model().objects.get(username=username)
#     if you in me.followings.all():
#         me.followings.remove(you)
#     else:
#         me.followings.add(you)

#     return redirect('accounts:profile', username)

QnA/templates/index.html
{% extends 'base.html' %}

{% block body %}

    <a href="{% url 'QnA:question' q_id=q_id %}">start</a>

{% endblock %}

QnA/templates/question.html
{% extends 'base.html' %}

{% block body %}

<div class="container text-center">
    <div class="row">
      <div class="col">
        {{question.content}}
      </div>
    </div>
    <div class="row">
      <div class="col">
        {{question.option1}} <br>
        <button href="{% url 'QnA:next_question' q_id=q_id %}" type="button" class="btn btn-primary btn-lg">Large button</button>
      </div>
      <div class="col">
        {{question.option2}} <br>
        <button href="{% url 'QnA:next_question' q_id=q_id %}" type="button" class="btn btn-primary btn-lg">Large button</button>
      </div>
    </div>
</div>
    
{% endblock %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block body %}

{% if request.resolver_match.url_name == 'signup' %}
    <h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
    <h1>로그인</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary">
    {% if request.resolver_match.url_name == 'login' %}
        <a href="{% url 'accounts:signup' %}">signup</a>
    {% endif %}
</form>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load bootstrap5 %}

{% block body %}

<div class="row">
  <div class="col-4">
    <img src="{{user_info.profile_image.url}}" alt="" class="img-fluid rounded-circle">
  </div>
  <div class="col-8">
    <div class="row">
      <div class="col-3">{{user_info.username}}</div>
      {% if user != user_info %}
      <div class="col-3">
        {% if user in user_info.followers.all %}
        <a href="{% url 'accounts:follow' username=user_info.username%}" class="btn btn-primary btn-sm">
          팔로잉
        </a>
        {% else %}
        <a href="{% url 'accounts:follow' username=user_info.username%}" class="btn btn-secondary btn-sm">
          팔로우
        </a>
        {% endif %}
      </div>
      {% endif %}
    </div>
    <div class="row">
      <div class="col"><p class="btn btn-secondary btn-sm">게시물 {{user_info.post_set.all|length}}</p></div>
      <div class="col">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            팔로워 {{user_info.followers.all|length}}
          </button>
          <ul class="dropdown-menu">
            {% for user_temp in user_info.followers.all %}
              <li><p class="dropdown-item">{{user_temp.username}}</p></li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="col">
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            팔로우 {{user_info.followings.all|length}}
          </button>
          <ul class="dropdown-menu">
            {% for user_temp in user_info.followings.all %}
              <li><p class="dropdown-item">{{user_temp.username}}</p></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row row-cols-3">
  {% for post in user_info.post_set.all %}
  <div class="col">
    <div class="card">
      <img src="{{post.image.url}}" alt="">
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>


    
    {% block body %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>